## Basic Configuration

baseurl = "https://zubala.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "../"

author = "Aleksander Zubala"
title = "Aleksander Zubala"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-90751160-1"
enableRobotsTXT = true

## Site Settings
[params]
author = "Aleksander Zubala"
intro = "Software Engineer"
description = "iOS Developer since 2010"
authorimage = "me.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Aleksander Zubala: iOS Developer"
keywords = "zubala,ios,swift,objective-c,apple,iphone,ipad,software,blog"

## Social Accounts
[params.social]
github = "azubala"
instagram = "alekzubala"
linkedin = "aleksanderzubala"
twitter = "alekzubala"
facebook = "aleksander.zubala"
google = "113073625905883377159"
stackoverflow = "4655732"
email = "alek@zubala.com"

## Extras
[params.extra]
copyright = "© 2019 Aleksander Zubala"
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "about me"
    identifier = "about"
    weight = 100
    url = "/about/"
# [[menu.main]]
#     name = "blog"
#     weight = 200
#     identifier = "blog"
#     url = "/blog/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"