# Site settings
title: Aleksander Zubala
email: alek@zubala.com
url: https://zubala.com
description: "Home page of Aleksander Zubala, iOS Developer since 2009. Contains his bio, portfolio and blog of the author"
skills: "Software Engineer - iOS Developer - AppCode fan"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Aleksander Zubala
  contactInfo: Contact
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/alekzubala
  - title: facebook
    url: https://www.facebook.com/aleksander.zubala
  - title: stack-overflow
    url: http://stackoverflow.com/users/4655732/aleksander-zubala
  - title: bitbucket
    url: http://bitbucket.org/azubala
  - title: github
    url: http://github.com/azubala

# Postal address (add as many lines as necessary)
contactInfo:  
  - line: 'azoobie Aleksander Zubala'
  - line: 'NIP: 951-215-44-84'
  - line: 'REGON: 147360180'
  - line: 'al. KEN 20/78'
  - line: '02-797 Warsaw, Poland'

# Credits content
credits:
 - line: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>'
 - line: 'Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>             is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a>'

# Build settings
markdown: kramdown
permalink: pretty
